package system.presentation.clientes;

import system.logic.Provincia;
import java.awt.Rectangle;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import java.util.Observable;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import system.logic.Canton;
import system.logic.Cliente;
import system.logic.Distrito;

public class View extends javax.swing.JFrame implements java.util.Observer {

//**************  MVC ***********
    Controller controller;
    Model model;

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public Controller getController() {
        return controller;
    }

    public void setModel(Model model) {
        this.model = model;
        model.addObserver(this);
    }

    public Model getModel() {
        return model;
    }

    @Override
    public void update(Observable o, Object arg) {
        Cliente cliente = model.getCliente();
        cedula.setText(cliente.getCedula());
        nombre.setText(cliente.getNombre());
        provincia.setText(cliente.getProvincia().getNombre());
        
        if(this.getProvinciaActual().getNombre() == ""){
            provinciaActual = cliente.getProvincia();
        }
        provincia.setText(this.getProvinciaActual().toString());
        
     //
     
       
        canton.setSelectedItem(cliente.getCanton());
        
        //distrito.setModel(new DefaultComboBoxModel(model.getDistritos().toArray()));
        distrito.setSelectedItem(cliente.getDistrito());
    }
//************** END MVC ***********

    public View() {
        initComponents();
        this.provinciaActual = new Provincia();
        loadMaps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblCedula = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jlblNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jlblProvincia = new javax.swing.JLabel();
        provincia = new javax.swing.JTextField();
        jlblCanton = new javax.swing.JLabel();
        canton = new javax.swing.JComboBox<>();
        jlbldistrito = new javax.swing.JLabel();
        distrito = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        mapaPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlblCedula.setText("Cedula");

        jlblNombre.setText("Nombre");

        jlblProvincia.setText("Provincia");

        jlblCanton.setText("Cantón");

        canton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonActionPerformed(evt);
            }
        });

        jlbldistrito.setText("Distrito");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        mapaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapas/CostaRica.png"))); // NOI18N
        mapaPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mapaPrincipalMouseMoved(evt);
            }
        });
        mapaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapaPrincipalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(canton, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbldistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(distrito, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mapaPrincipal))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCedula)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblProvincia)
                    .addComponent(jlblCanton)
                    .addComponent(jlbldistrito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addGap(28, 28, 28)
                .addComponent(mapaPrincipal)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        controller.clienteGet(cedula.getText());
        Cliente cliente = model.getCliente();
        if(!cliente.equals(new Cliente()))
        {
            canton.setModel(new DefaultComboBoxModel(controller.getCantones(cliente.getProvincia().getNombre()).toArray()));
            canton.setSelectedItem(cliente.getCanton());
            distrito.setModel(new DefaultComboBoxModel(controller.getDistritos(cliente.getCanton().getNombre()).toArray()));
            distrito.setSelectedItem(cliente.getDistrito());
        }
        provincia.setText(cliente.getProvincia().getNombre());
        mapaPrincipal.setIcon(maps[Integer.parseInt(cliente.getProvincia().getNumero())]);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void mapaPrincipalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaPrincipalMouseMoved

        Provincia result = controller.getProvincia(evt.getX(), evt.getY());
        if (!result.equals(new Provincia())) {
            int i = Integer.parseInt(result.getNumero());
            mapaPrincipal.setIcon(maps[i]);
        }

    }//GEN-LAST:event_mapaPrincipalMouseMoved

    private void mapaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaPrincipalMouseClicked
        this.setProvinciaActual(controller.getProvincia(evt.getX(), evt.getY()));
        Provincia resultProvincia = this.getProvinciaActual();
        if (!resultProvincia.equals(new Provincia())) {
            this.provincia.setText(resultProvincia.getNombre());
            int i = Integer.parseInt(resultProvincia.getNumero());
            mapaPrincipal.setIcon(maps[i]);
        }
        canton.setModel(new DefaultComboBoxModel(controller.getCantones(resultProvincia.getNombre()).toArray()));
//        canton.setSelectedIndex(0);
       // distrito.setModel(new DefaultComboBoxModel(controller.getDistritos(canton.getSelectedItem().toString()).toArray()));
//        distrito.setSelectedIndex(0);
        this.provincia.setText(resultProvincia.getNombre());
    }//GEN-LAST:event_mapaPrincipalMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        controller.clienteAdd(new Cliente(cedula.getText(), nombre.getText(), this.getProvinciaActual(), (Canton) canton.getSelectedItem(), (Distrito) distrito.getSelectedItem()));
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonActionPerformed
        String nombreCanton = canton.getSelectedItem().toString();
        distrito.setModel(new DefaultComboBoxModel(controller.getDistritos(nombreCanton).toArray()));
        this.provincia.setText(this.getProvinciaActual().getNombre());
    }//GEN-LAST:event_cantonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.exit();
    }//GEN-LAST:event_formWindowClosing

    private Provincia getProvinciaActual() {
        return provinciaActual;
    }

    private void setProvinciaActual(Provincia provinciaActual) {
        this.provinciaActual = provinciaActual;
    }

    private Provincia provinciaActual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Canton> canton;
    private javax.swing.JTextField cedula;
    private javax.swing.JComboBox<Distrito> distrito;
    private javax.swing.JLabel jlblCanton;
    private javax.swing.JLabel jlblCedula;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblProvincia;
    private javax.swing.JLabel jlbldistrito;
    private javax.swing.JLabel mapaPrincipal;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField provincia;
    // End of variables declaration//GEN-END:variables
 int n = 8;
    ImageIcon[] maps;

    private void loadMaps() {
        maps = new ImageIcon[n];

        try {
            maps[0] = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/mapas/CostaRica.png")));
            for (int p = 1; p < n; p++) {
                maps[p] = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/mapas/" + p + ".png")));
            }
        } catch (IOException e) {
            System.err.println(e);
        }
    }
}
